variables:
  DEPLOY_ENVIRONMENT:
    value: "staging"  # Deploy to staging by default
    description: "The deployment target. Change this variable to 'canary' or 'production' if needed."
  CI_DEBUG_TRACE: "true"

include:
  - project: 'infinity-economics/iep-infrastructure'
    file: '/gitlab-ci/docker-build-publish.yml'